import { db, emailThreatsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

export async function seedEmailThreats() {
  const [count] = await db.select({ count: sql<number>`count(*)::int` }).from(emailThreatsTable);
  if ((count?.count ?? 0) > 0) return;

  console.log("Seeding email threats...");
  await db.insert(emailThreatsTable).values([
    { subject: "Urgent: Verify your PayPal account immediately", sender: "security@paypa1-verify.com", recipient: "admin@corp.com", threatType: "phishing", riskScore: 0.95, status: "blocked", senderReputation: 0.05, hasAttachment: false, country: "NG", ipAddress: "41.203.67.12", details: "Domain spoofing PayPal. Contains credential harvesting link.", quarantined: false },
    { subject: "Invoice #INV-2847 - Payment Required", sender: "billing@fake-vendor.ru", recipient: "finance@corp.com", threatType: "bec", riskScore: 0.88, status: "quarantined", senderReputation: 0.12, hasAttachment: true, attachmentName: "invoice_2847.pdf", attachmentScanResult: "Embedded JavaScript detected", country: "RU", ipAddress: "185.220.101.34", details: "Business email compromise attempt. Unknown vendor domain.", quarantined: true },
    { subject: "Your package delivery notification", sender: "noreply@fedex-tracking.xyz", recipient: "hr@corp.com", threatType: "phishing", riskScore: 0.91, status: "blocked", senderReputation: 0.08, hasAttachment: true, attachmentName: "tracking_label.exe", attachmentScanResult: "Trojan.GenericKD detected", country: "CN", ipAddress: "103.44.55.22", details: "Fake shipping notification with malware dropper attachment.", quarantined: false },
    { subject: "RE: Q4 Financial Report - Updated Numbers", sender: "cfo@c0rp-internal.com", recipient: "ceo@corp.com", threatType: "spoofing", riskScore: 0.85, status: "quarantined", senderReputation: 0.15, hasAttachment: true, attachmentName: "Q4_Report_Final.xlsm", attachmentScanResult: "Macro with suspicious VBA code", country: "IR", ipAddress: "5.34.178.99", details: "Internal spoofing attempt. Domain mimics corp-internal.com.", quarantined: true },
    { subject: "Congratulations! You've won a $1000 gift card", sender: "promotions@deals-winner.net", recipient: "all-staff@corp.com", threatType: "spam", riskScore: 0.45, status: "blocked", senderReputation: 0.20, hasAttachment: false, country: "US", ipAddress: "198.51.100.42", details: "Mass spam campaign. Known spam sender domain.", quarantined: false },
    { subject: "Critical Security Update Required", sender: "it-support@micros0ft-update.com", recipient: "tech@corp.com", threatType: "phishing", riskScore: 0.92, status: "detected", senderReputation: 0.07, hasAttachment: true, attachmentName: "security_patch.msi", attachmentScanResult: "Ransomware payload detected", country: "KP", ipAddress: "175.45.176.3", details: "Impersonating Microsoft. Attachment contains ransomware.", quarantined: false },
    { subject: "Wire Transfer Authorization - $45,000", sender: "ceo-office@corp-mgmt.io", recipient: "finance@corp.com", threatType: "bec", riskScore: 0.94, status: "blocked", senderReputation: 0.10, hasAttachment: false, country: "NG", ipAddress: "41.58.172.88", details: "CEO fraud attempt. Requesting unauthorized wire transfer.", quarantined: false },
    { subject: "Share document: Salary Review 2026.docx", sender: "hr-admin@googledocs-share.com", recipient: "employees@corp.com", threatType: "phishing", riskScore: 0.87, status: "quarantined", senderReputation: 0.11, hasAttachment: false, country: "RU", ipAddress: "95.142.206.1", details: "Fake Google Docs share link. Credential harvesting page.", quarantined: true },
    { subject: "Account Suspension Notice - Action Required", sender: "support@aws-billing.net", recipient: "devops@corp.com", threatType: "phishing", riskScore: 0.89, status: "detected", senderReputation: 0.09, hasAttachment: false, country: "CN", ipAddress: "116.31.116.42", details: "AWS impersonation. Phishing link to fake login page.", quarantined: false },
    { subject: "Meeting notes from yesterday", sender: "colleague@partner-firm.com", recipient: "manager@corp.com", threatType: "malware", riskScore: 0.78, status: "quarantined", senderReputation: 0.30, hasAttachment: true, attachmentName: "meeting_notes.docm", attachmentScanResult: "Macro downloader detected", country: "DE", ipAddress: "89.163.145.67", details: "Compromised partner account. Attachment downloads second-stage malware.", quarantined: true },
    { subject: "Pharmacy discounts - limited time offer!", sender: "deals@cheap-pharmacy.biz", recipient: "all-staff@corp.com", threatType: "spam", riskScore: 0.35, status: "blocked", senderReputation: 0.15, hasAttachment: false, country: "IN", ipAddress: "49.36.121.77", details: "Pharmaceutical spam. Known spam operation.", quarantined: false },
    { subject: "Tax Return Document - IRS Notice", sender: "notices@irs-refund.org", recipient: "finance@corp.com", threatType: "phishing", riskScore: 0.93, status: "blocked", senderReputation: 0.04, hasAttachment: true, attachmentName: "tax_notice_2026.pdf", attachmentScanResult: "PDF exploit CVE-2025-1234", country: "NG", ipAddress: "41.190.2.55", details: "IRS impersonation during tax season. PDF contains exploit.", quarantined: false },
  ]);
  console.log("Email threats seeded.");
}
