import { Router, type IRouter } from "express";
import healthRouter from "./health";
import transactionsRouter from "./transactions";
import approvalsRouter from "./approvals";
import dashboardRouter from "./dashboard";
import alertsRouter from "./alerts";
import integrationsRouter from "./integrations";
import monitoringRouter from "./monitoring";
import darkWebRouter from "./dark-web";
import emailSecurityRouter from "./email-security";
import endpointsRouter from "./endpoints";
import networkRouter from "./network";
import yubikeyRouter from "./yubikey";
import openclawRouter from "./openclaw";
import recoveryRouter from "./recovery";
import disasterRecoveryRouter from "./disaster-recovery";
import threatsRouter from "./threats";
import backupsRouter from "./backups";
import lockdownRouter from "./lockdown";
import aiRouter from "./ai";
import workspaceMonitorRouter from "./workspace-monitor";
import threatIntelRouter from "./threat-intel";
import ipManagementRouter from "./ip-management";
import breachRouter from "./breach";
import gatewayRouter from "./gateway";
import securityAgentRouter from "./security-agent";
import securitySettingsRouter from "./security-settings";
import selfScanRouter from "./self-scan";
import domainMonitorRouter from "./domain-monitor";
import secureVaultRouter from "./secure-vault";
import threatDetectionRouter from "./threat-detection";

const router: IRouter = Router();

router.use(healthRouter);
router.use(transactionsRouter);
router.use(approvalsRouter);
router.use(dashboardRouter);
router.use(alertsRouter);
router.use(integrationsRouter);
router.use(monitoringRouter);
router.use(darkWebRouter);
router.use(emailSecurityRouter);
router.use(endpointsRouter);
router.use(networkRouter);
router.use(yubikeyRouter);
router.use(openclawRouter);
router.use(recoveryRouter);
router.use(disasterRecoveryRouter);
router.use(threatsRouter);
router.use(backupsRouter);
router.use(lockdownRouter);
router.use(aiRouter);
router.use(workspaceMonitorRouter);
router.use(threatIntelRouter);
router.use(ipManagementRouter);
router.use(breachRouter);
router.use(gatewayRouter);
router.use(securityAgentRouter);
router.use(securitySettingsRouter);
router.use(selfScanRouter);
router.use(domainMonitorRouter);
router.use(secureVaultRouter);
router.use(threatDetectionRouter);

export default router;
