import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import transactionsRouter from "./transactions";
import approvalsRouter from "./approvals";
import dashboardRouter from "./dashboard";
import alertsRouter from "./alerts";
import integrationsRouter from "./integrations";
import monitoringRouter from "./monitoring";
import darkWebRouter from "./dark-web";
import emailSecurityRouter from "./email-security";
import endpointsRouter from "./endpoints";
import networkRouter from "./network";
import yubikeyRouter from "./yubikey";
import openclawRouter from "./openclaw";
import recoveryRouter from "./recovery";
import disasterRecoveryRouter from "./disaster-recovery";
import threatsRouter from "./threats";
import backupsRouter from "./backups";
import lockdownRouter from "./lockdown";
import aiRouter from "./ai";
import workspaceMonitorRouter from "./workspace-monitor";
import threatIntelRouter from "./threat-intel";
import ipManagementRouter from "./ip-management";
import breachRouter from "./breach";
import gatewayRouter from "./gateway";
import securityAgentRouter from "./security-agent";
import securitySettingsRouter from "./security-settings";
import selfScanRouter from "./self-scan";
import domainMonitorRouter from "./domain-monitor";
import secureVaultRouter from "./secure-vault";
import threatDetectionRouter from "./threat-detection";
import usersRouter from "./users";
import virustotalRouter from "./virustotal";
import travelSecurityRouter from "./travel-security";
import remoteMaintenanceRouter from "./remote-maintenance";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(transactionsRouter);
router.use(approvalsRouter);
router.use(dashboardRouter);
router.use(alertsRouter);
router.use(integrationsRouter);
router.use(monitoringRouter);
router.use(darkWebRouter);
router.use(emailSecurityRouter);
router.use(endpointsRouter);
router.use(networkRouter);
router.use(yubikeyRouter);
router.use(openclawRouter);
router.use(recoveryRouter);
router.use(disasterRecoveryRouter);
router.use(threatsRouter);
router.use(backupsRouter);
router.use(lockdownRouter);
router.use(aiRouter);
router.use(workspaceMonitorRouter);
router.use(threatIntelRouter);
router.use(ipManagementRouter);
router.use(breachRouter);
router.use(gatewayRouter);
router.use(securityAgentRouter);
router.use(securitySettingsRouter);
router.use(selfScanRouter);
router.use(domainMonitorRouter);
router.use(secureVaultRouter);
router.use(threatDetectionRouter);
router.use(usersRouter);
router.use(virustotalRouter);
router.use(travelSecurityRouter);
router.use(remoteMaintenanceRouter);

router.get("/endpoints/patches", (req, res) => res.redirect(307, `/api/endpoints/patch-compliance`));
router.get("/endpoints/usb", (req, res) => res.redirect(307, `/api/endpoints/usb-monitor`));
router.get("/endpoints/behavior", (req, res) => res.redirect(307, `/api/endpoints/behavioral-analytics`));
router.get("/endpoints/malware", (req, res) => res.redirect(307, `/api/endpoints/malware-scans`));
router.get("/email-security/auth", (req, res) => res.redirect(307, `/api/email-security/auth-monitor`));
router.get("/email-security/attachments", (req, res) => res.redirect(307, `/api/email-security/attachment-analysis`));
router.get("/email-security/compromise", (req, res) => res.redirect(307, `/api/email-security/account-compromise`));
router.get("/email-security/phishing", (req, res) => res.redirect(307, `/api/email-security/phishing-campaigns`));
router.get("/network/intrusions", (req, res) => res.redirect(307, `/api/network/ids`));
router.get("/network/dns", (req, res) => res.redirect(307, `/api/network/dns-security`));
router.get("/network/vpn", (req, res) => res.redirect(307, `/api/network/vpn-zerotrust`));
router.get("/network/firewall", (req, res) => res.redirect(307, `/api/network/firewall-rules`));
router.get("/openclaw/api", (req, res) => res.redirect(307, `/api/openclaw/api-security`));
router.get("/openclaw/drift", (req, res) => res.redirect(307, `/api/openclaw/config-drift`));

export default router;
